travis:
  secure:
    BINSTAR_TOKEN: KtEULZMZT8IRYZmyCS36qiIVIh7/OYFRRw5u48UHWBkRz1zey9xq6b/jUMb1YcBF/IoMydtXJeQ3zq4G+dAEW1HEG94QNJI2e8WP084oyOw7LdW56K9a5FM5vlXcPXig7++qe0QN1d2VeJaoBdbGu9TsErriYvaWJXV3irWMbHqyIomvu48pg9DgXVoAAPKUfIUIf+krlMHwlR5M/Hr9VClxnj/p1IaJroCVv9eSS++GT2id9NgAP0TxucdbsiF/FiVetkVR98LBfTsfURCr0oyzF9UED/bBVLMI/sN4KfDF+fmVwX2Af+jXZgCNczs5VbfWVcrViPtH4BfQtyoRGe8GpLstQId1lZxPN6mPzFcDOu7zmAlQL+oFCtQ9mus1KGjEv2pAj2iCovgCY8rEgtSmyqmA9QYGJj946fnPre0BvE/19TbMeSBmnx2jDr2dwmGQuKqGmVDzkjWbMHP9Ej7ON5YR6lVP1Hk2cBmnGcGuC4tXIaEFkz/T7ETPrkk1prquGgGFddv5zmQ045ApIKaCQxatnVWwr7QvwM3WUIVq1MoCZ9XX7MvpyIT5lTeCV/alu5qH1rNlNANSL/6p/8pHzRSoichm8syNxEC1jrUg3o16x7RolWu24Wf6tVveJjuJIDJXlXrv2seV8T+SMLZ7Wrx59WUwsD3U1jsNsR8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
